[package]
name = "nomos-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.9"
chrono = "0.4.38"

[lib]
name = "nomos_rust"
path = "src/lib.rs"
